# Generated by Django 4.2.29 on 2026-03-24 02:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VitaminLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vitamin_type",
                    models.CharField(
                        choices=[
                            ("vitamin_a", "Vitamin A"),
                            ("vitamin_b6", "Vitamin B6"),
                            ("vitamin_b12", "Vitamin B12"),
                            ("vitamin_c", "Vitamin C"),
                            ("vitamin_d", "Vitamin D"),
                            ("vitamin_e", "Vitamin E"),
                            ("vitamin_k", "Vitamin K"),
                            ("iron", "Iron"),
                            ("calcium", "Calcium"),
                            ("magnesium", "Magnesium"),
                            ("zinc", "Zinc"),
                            ("other", "Other"),
                        ],
                        max_length=32,
                    ),
                ),
                ("custom_vitamin_name", models.CharField(blank=True, max_length=80)),
                (
                    "intake_source",
                    models.CharField(
                        choices=[
                            ("food", "Food"),
                            ("supplement", "Supplement"),
                            ("both", "Both"),
                        ],
                        default="food",
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=7)),
                (
                    "unit",
                    models.CharField(
                        choices=[("mg", "mg"), ("mcg", "mcg"), ("iu", "IU")],
                        default="mg",
                        max_length=8,
                    ),
                ),
                (
                    "logged_for",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vitamin_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-logged_for", "-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="vitaminlog",
            constraint=models.CheckConstraint(
                check=models.Q(("amount__gt", 0)), name="tracking_amount_gt_zero"
            ),
        ),
    ]
